<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            array('name'=>'Cepmox-Clav 875mg/125mg', 'type_id'=>4, 'describe'=>'Không có', 'info'=>'Sản phẩm này chỉ bán khi có chỉ định của bác sĩ, mọi thông tin trên Website, App chỉ mang tính chất tham khảo. Vui lòng xác nhận bạn là dược sĩ, bác sĩ, nhân viên y tế có nhu cầu tìm hiểu về sản phẩm này', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P25617_1N.jpg', 'slug' => 'cepmox-clav-875mg-125mg', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'),'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Men vi sinh hỗ trợ tiêu hóa BIFISANFO Plus', 'type_id'=>7, 'describe'=>'Mỗi gói 3g chứa: Fructose oligosaccharide (FOS) 500 mg; Cao Bạch phục linh 100 mg; Cao Mộc hoa trắng 100 mg; Immunepath-IP 100 mg; Curcumin phytosome 50 mg; 5-HTP 3 mg; Bifidobacterium lactis 108 CFU; Bifidobacterium longum 108 CFU; Lactobacillus acidophilus 108 CFU; Lacto bacillus caisei 108 CFU; Phụ liệu (Bột kem, Đường kính, Lactose) vừa đủ 3 g.', 'info'=>'Hỗ trợ giảm các triệu chứng của viêm đại tràng và hội chứng ruột kích thích như: đi ngoài nhiều lần trong ngày, đi ngoài phân lỏng, đau bụng. Hỗ trợ cân bằng hệ vi khuẩn có ích đường ruột, hỗ trợ tăng sức đề kháng và tăng cường sức khỏe hệ tiêu hóa.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P25862_1.jpg', 'slug' => 'men-vi-sinh-ho-tro-tieu-hoa-BIFISANFO-Plus', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Dầu dưỡng giúp mờ sẹo & giảm rạn da Bio-Oil', 'type_id'=>1, 'describe'=>'Dầu Khoáng Chất, Trilsononaoin, Cetearyl Ethylhexanoat, Isopropyl Myristat, Vitamin A, Tinh Dầu Hạt Hướng Dương, Vitamin E, Tinh Dầu Cúc La Mã, Tinh Dầu Oải Hương, Tinh Dầu Lá Hương Thảo, Chiết Xuất Cúc Xu Xi, Tinh Dầu Đậu Tương Leo, BHT, Tinh Dầu Hoa Cúc, Chất Thơm, Alpha – Isomethyl Ionon, Amyl Cinnamal, Benzyl Salicylat, Citronellol, Coumarin, Eugenol, Farmesol, Geraniol, Hydroxycitronellal, Hydroxyisohexyl 3-Cyclohexen Carboxaldehyd, Limonen, Linalool, CI 26100', 'info'=>'Giúp cải thiện tình trạng bên ngoài của sẹo, vết rạn da và da không đều màu. Sản phẩm này cũng được khuyên dùng cho da bị lão hóa và da bị mất nước.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P01977_1.jpg', 'slug' => 'dau-duong-giup-mo-seo-&-giam-ran-da-Bio-Oil', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Khăn giấy ướt hương nhẹ an toàn cho bé Agi', 'type_id'=>8, 'describe'=>'Không có', 'info'=>'Mở nắp hộp, gỡ tem phía trong, rút từng tờ để sử dụng. Sau khi dùng xong đóng nắp hộp lai để giữ ẩm và kháng khuẩn.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P08882.png', 'slug' => 'khan-giay-uot-huong-nhe-an-toan-cho-be-Agi', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Giấy vệ sinh Pharmacity', 'type_id'=>8, 'describe'=>'100% bột giấy nguyên chất.', 'info'=>'Giấy vệ sinh Pharmacity 3 lớp ply mềm mại, dai và thấm hút.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P18568.png', 'slug' => 'giay-ve-sinh-Pharmacity', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Sữa nước hương vani Abbott PediaSure cho trẻ 1-10 tuổi 180ml', 'type_id'=>5, 'describe'=>'Sữa nước hương vani Abbott PediaSure cho trẻ 1-10 tuổi 180ml bao gồm trẻ tăng trưởng kém (nhẹ cân, thấp còi, suy dinh dưỡng, hay ốm), trẻ biếng ăn, trẻ có nhu cầu năng lượng tăng cao.', 'info'=>'Sữa giàu Vitamins C, E & Selenium, thơm mùi vani được nhiều bé yêu thích, bổ sung thêm chất xơ trong thành phần dinh dưỡng giúp hỗ trợ hệ tiêu hóa tối đa, đẩy mạnh quá trình trao đổi chất, tăng khả năng hấp thu.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P18087.png', 'slug' => 'sua-nuoc-huong-vani-Abbott-PediaSure-cho-tre-1-10-tuoi-180ml', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Dầu gội trẻ em dạng sữa Cetaphil Baby Gentle Wash & Shampoo', 'type_id'=>5, 'describe'=>'Aqua, Sorbitol, Cocamidopropyl Betaine, Lauryl Glucoside, Glycerin, Panthenol, Coco-Glucoside, Glyceryl Oleate, Acrylates/C10-30 Alkyl Acrylate Rosspolymer, Aloe Barbadensis Leaf Juice Powder, Chamomilla Recutita Flower Extract, Citric Acid, Heliotropine, Hydrogenated Palm Glycerides Citrate, Hydrolyzed Wheat Protein, Parfum, Sodium Hydroxide, Tocopherol, Zinc Sulfate.', 'info'=>'Dầu gội dạng sữa Cetaphil Baby Gentle Wash & Shampoo chứa các thành phần rất lành tính và dịu nhẹ mang đến những ưu điểm “đẹp như mơ” dành cho các bé yêu. Với chiết xuất hoa cúc hữu cơ giúp cung cấp độ ẩm làm mềm da, cân bằng độ pH, làm dịu vùng da kích ứng và tăng tính đàn hồi cho da bé. Ngoài ra còn chứa thành phần glycerin và panthenol có tác dụng làm mềm mịn và dưỡng ẩm da tự nhiên, đồng thời hỗ trợ làm giảm da khô hay bong tróc.', 
            'price'=>200000, 'quantity' => 100, 'img'=>'P09428_3.jpg', 'slug' => 'Dau-goi-tre-em-dang-sua-Cetaphil-Baby-Gentle-Wash-&-Shampoo', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Hộp que thử Contour Plus', 'type_id'=>6, 'describe'=>'Que thử được thiết kế để dễ dàng "trích" lấy máu vào đầu mẫu thử. Chỉ cần mẫu máu nhỏ 0,6 μL.  Sử dụng que thử trước thời hạn sử dụng. Nhận kết quả sau 5 giây. Khả năng lấy mẫu Second-Chance cho phép bạn lấy thêm máu khi lượng máu lúc đầu không đủ để xét nghiệm', 'info'=>'Kết quả chính xác, Tiết kiệm que thử, Trả kết quả sau 5 giây', 
            'price'=>300000, 'quantity' => 100, 'img'=>'nqMjjvMJI0CYECRR5dcnx96HwgwAPKrx.jpg', 'slug' => 'Hop-que-thu-Contour-Plus', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Acetylcystein 200mg Vidipha (Hộp 20 vỉ x 10 viên)', 'type_id'=>4, 'describe'=>'Mỗi gói 1g có chứa: Acetylcystein 200mg, lactose monohydrat, aspartam, acid ascorbic, màu vàng số 6 lake, mùi cam, silicon dioxid.', 'info'=>'Điều trị rối loạn tiết dịch phế quản, đặc biệt là trong các rối loạn phế quản cấp tính như viêm phế quản cấp và bệnh phổi tắc nghẽn mãn tính.', 
            'price'=>55000, 'quantity' => 100, 'img'=>'P17480_11.png', 'slug' => 'Acetylcystein-200mg-Vidipha-Hop-20-vi-x-10-vien', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Avircrem 5g (Hộp 1 tuýp)', 'type_id'=>4, 'describe'=>'Acyclovir 250mg, Cremophor A6, Cremophor A25, Celos†edryi Alcohol, Glyceryl monosfedrdt, lsoproDyl myristat, Paroffin lỏng, SimeThicon, Propylen glycol, Dinatri ederot, Methylpdraben, Propyiparaben, Nước tinh khiết', 'info'=>'Điều trị các trường hợp nhiễm virus Herpes simplex trên da.', 
            'price'=>25000, 'quantity' => 100, 'img'=>'P19451_1_l.png', 'slug' => 'Avircrem-5g-Hop-1-tuyp', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Jazxylo 0,05% Drops (Chai 10ml)', 'type_id'=>4, 'describe'=>'Xylometazolin hydroclorid 5mg, Tá dược (natri dihydro phosphat dihydrat, dinatri phosphat dodecahydrat, dinatri edetat, benzalkonium clorid, hydroxypropyl methyl cellulose, natri clorid, sorbitol 70%, nước tinh khiết) vừa đủ 10ml.', 'info'=>'Giảm triệu chứng ngạt mũi, sổ mũi và giảm sung huyết trong các trường hợp viêm mũi cấp hoặc mạn tính, viêm xoang, cảm lạnh, cảm mạo hoặc dị ứng đường hô hấp trên.', 
            'price'=>250000, 'quantity' => 100, 'img'=>'P26146.png', 'slug' => 'jazxylo-005-drops-chai-10ml', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Katrypsin 8400Iu (Hộp 10 vỉ x10 viên)', 'type_id'=>4, 'describe'=>'Alphachymotrypsin 8400IU', 'info'=>'Điều trị các trường hợp viêm và phù nề sau chấn thương, bỏng và sau phẫu thuật. Thuốc Katrypsin Fort chống chỉ định cho bệnh nhân quá mẫn cảm với Alphachymotrypsin và các thành phần của thuốc.', 
            'price'=>250000, 'quantity' => 100, 'img'=>'P26144_1.jpg', 'slug' => 'katrypsin-8400iu-hop-10-vi-x10-vien', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Levothyrox 100mcg (2 vỉ x 15 viên)', 'type_id'=>4, 'describe'=>'Mỗi viên Levothyrox® 100mcg chứa: 100mcg Levothyroxine natri. Thành phần tá dược: Tinh bột ngô, acid citric khan, natri croscarmellose, gelatine, magie stearate, mannitol.', 'info'=>'Áp dụng cho các thuốc Levothyrox® có hàm lượng từ 25 đến 100mcg: Điều trị bướu giáp đơn thuần lành tính, Dự phòng tái phát sau phẫu thuật bướu giáp đơn thuần, tùy thuộc vào tình trạng hormon sau phẫu thuật, Điều trị thay thế trong suy giáp, Điều trị ức chế trong ung thư giáp, Phối hợp với thuốc kháng giáp trong điều trị cường giáp.', 
            'price'=>300000, 'quantity' => 100, 'img'=>'P26254_1.jpg', 'slug' => 'levothyrox-100mcg-2-vi-x-15-vien', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Reprat (Hộp 2 vỉ x 10 viên)', 'type_id'=>4, 'describe'=>'Thành phần: PANTOPRAZOLE 40 MG', 'info'=>'Ðiều trị trào ngược dạ dày - thực quản. Người lớn: Phối hợp với liệu pháp kháng sinh thích hợp để diệt Helicobacter pylori (H.pylori) ở bệnh nhân loét dạ dày do H.pylori. Ðiều trị loét dạ dày và tá tràng. Điều trị hội chứng Zollinger Ellison và các tình trạng tăng tiết bệnh lý khác.', 
            'price'=>252000, 'quantity' => 100, 'img'=>'P24807_1.jpg', 'slug' => 'reprat-hop-2-vi-x-10-vien', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Siro Bảo Thanh (90ml)', 'type_id'=>4, 'describe'=>'Hoạt chất: Xuyên bối mẫu0,4g, Tỳ bà diệp 0,5g; Sa sâm 0,1g; Trần bì 0,1g; Cát cánh 0,4g; ...', 'info'=>'Công dụng: Điều trị các chứng ho do cảm lạnh, nhiễm lạnh, ho gió, ho khan...', 
            'price'=>252000, 'quantity' => 100, 'img'=>'P11034.png', 'slug' => 'siro-bao-thanh-90ml', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Kem chống nắng Avene Protection Fluid 50+ Blue Light (Chai 50ml)', 'type_id'=>2, 'describe'=>'AVENE THERMAL SPRING WATER (AVENE AQUA). C12-15 ALKYL BENZOATE. DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE (Uvinul A plus - UV filter). ETHYLHEXYL TRIAZONE (Uvinul T150 - UV filter). ORYZA SATIVA (RICE) STARCH (ORYZA SATIVA STARCH). PHENYLENE BIS-DIPHENYLTRIAZINE (TriAsorB-UV filter). WATER (AQUA). GLYCERIN. BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE (Tinosorb S- UV filter). POTASSIUM CETYL PHOSPHATE. GLYCERYL STEARATE. STEARYL ALCOHOL. TAPIOCA STARCH. VP/EICOSENE COPOLYMER. BENZOIC ACID. CAPRYLIC/CAPRIC TRIGLYCERIDE. CAPRYLYL GLYCOL. FRAGRANCE (PARFUM), GLYCERYL BEHENATE. GLYCERYL DIBEHENATE. PG-1-PEG-9 LAURYL GLYCOL ETHER. RED 33 (CI 17200). TOCOPHERYL GLUCOSIDE. TRIBEHENIN. XANTHAN GUM.', 'info'=>'Sữa chống nắng quang phổ rộng cho da thường, hỗn hợp nhạy cảm AVÈNE PROTECTION FLUID 50+ BLUE LIGHT', 
            'price'=>777000, 'quantity' => 100, 'img'=>'P27215_1.jpg', 'slug' => 'kem-chong-nang-avene-protection-fluid-50-blue-light-chai-50ml', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Kem chống nắng Cancer Council Everyday Value Sunscreen SPF50 (Chai 110ml)', 'type_id'=>2, 'describe'=>'AQUA, ISOPROPYL PALMITATE, OCTOCRYLENE, HOMOSALATE, BUTYL METHOXYDIBENZOYLMETHANE, ALCOHOL DENAT, GLYCERIN, SILICA, POLYGLYCERYL-3 DIISOSTEARATE, PVP/HEXADECENE COPOLYMER, CETEARYL ALCOHOL, PHENOXYETHANOL', 'info'=>'Kem chống nắng cho da hàng ngày, đồng thời giúp cung cấp độ ẩm cho da. Sản phẩm thích hợp cho da nhạy cảm', 
            'price'=>316000, 'quantity' => 100, 'img'=>'P25518.png', 'slug' => 'kem-chong-nang-cancer-council-everyday-value-sunscreen-spf50-chai-110ml', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Băng vệ Laurier Fresh & Free siêu mỏng cánh siêu thấm tối đa (Gói 20 miếng)', 'type_id'=>1, 'describe'=>'Bột giấy, vải không dệt, màng đáy, giấy, keo dính,...', 'info'=>'Băng vệ sinh ban ngày siêu mỏng cánh Laurier Fresh & Free chất lượng Nhật Bản với bề mặt rãnh caro đột phá thoáng nhẹ như không, thấm nhanh gấp 2 lần. Bề mặt mềm mại và êm dịu giúp nâng niu vùng da nhạy cảm của bạn, giữ cảm giác khô thoáng suốt nhiều giờ, nhờ đó các nàng sẽ thoải mái vận động cả ngày dài.', 
            'price'=>33000, 'quantity' => 100, 'img'=>'P17506_1.jpg', 'slug' => 'bang-ve-laurier-fresh-free-sieu-mong-canh-sieu-tham-toi-da-goi-20-mieng', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Băng vệ sinh ban đêm Diana Sensi Night 29cm (4 miếng/gói)', 'type_id'=>2, 'describe'=>'Bông Cellulose, hạt siêu thấm, PE, giấy, giấy tráng Silicone, Polymer kết dính, Vitamin E, mùi hương.', 'info'=>'Băng vệ sinh ban đêm Diana Sensi Night thiết kế miếng băng dài 29cm, bề mặt lưới được lụa hóa siêu mềm mịn và hệ thống rãnh bảo vệ khóa chất lỏng vào ban đêm, chống tràn, ngăn thấm ngược, mang lại cảm giác an toàn, thoải mái trong mọi tư thế ngủ. Thiết kế gọn nhẹ, tiện lợi mang theo mọi nơi.', 
            'price'=>16000, 'quantity' => 100, 'img'=>'P04695.png', 'slug' => 'bang-ve-sinh-ban-dem-diana-sensi-night-29cm-4-mieng-goi', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
            array('name'=>'Bánh sô cô la KitKat (35g)', 'type_id'=>8, 'describe'=>'Sữa bột nguyên kem, bột mì, bơ cacao, vụn cacao, dầu thực vật, muối, đường, carbohydrate…', 'info'=>'Bánh sô cô la KitKat là sự hòa quyện độc đáo giữa vị ngọt ngào của sô cô la, vị béo ngậy của sữa, độ xốp, giòn của bánh, mang đến cho bạn hương vị thơm ngon, hấp dẫn. Sản phẩm được làm từ các thành phần tự nhiên, không chứa chất tạo màu, chất bảo quản độc hại, an toàn với sức khỏe.', 
            'price'=>18000, 'quantity' => 100, 'img'=>'P07204_1_l.png', 'slug' => 'banh-so-co-la-kitkat-35g', 'created_at'=>Carbon::now('Asia/Ho_Chi_Minh'), 'updated_at'=>Carbon::now('Asia/Ho_Chi_Minh')),
        ]);
    }
}